config/routes.rb
Rails.application.routes.draw do
  resources :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table

  validates :table_id, presence: true
  validates :begin_at, presence: true
  validates :guest_count, presence: true

  def initialize(attributes = nil, options = {})

    table = Restaurant.find(attributes[:restaurant_id]).find_open_table(attributes[:begin_at], attributes[:guest_count])
    if (table)
      attributes[:table_id] = table.id
    end
    attributes.tap { |hs| hs.delete(:restaurant_id) }
    super

  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :tables
  has_many :reservations, through: :tables

  def find_open_table(begin_at, guest_count)

    self.tables.where("seat_count >= ?", guest_count).each do |t|
      if t.is_available(begin_at)
        return t
      end
    end
    nil
  end
end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :restaurant
  has_many :reservations

  def is_available(begin_at)

    if self.reservations.where(begin_at: (begin_at.to_time(:utc) - 2.hours).to_datetime..(begin_at.to_time(:utc) + 1.minute).to_datetime).count > 0
      return false
    end
    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:begin_at, :restaurant_id, :guest_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odrestaurants</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begin_at %><br>
    <%= f.datetime_select :begin_at %>
  </div>
  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.text_field :table_id %>
  </div>
  <div class="field">
    <%= f.label :guest_count %><br>
    <%= f.number_field :guest_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Begin at</th>
      <th>Table</th>
      <th>Guest count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.begin_at %></td>
        <td><%= reservation.table %></td>
        <td><%= reservation.guest_count %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Begin at:</strong>
  <%= @reservation.begin_at %>
</p>

<p>
  <strong>Table:</strong>
  <%= @reservation.table %>
</p>

<p>
  <strong>Guest count:</strong>
  <%= @reservation.guest_count %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>